#include "ConditionCatalog.h"

#include <algorithm>
#include <array>
#include <initializer_list>
#include <memory>

namespace {
    constexpr std::array<ConditionCatalog::FunctionInfo, 402> FUNCTIONS{{
        { 0u, "GetWantBlocking", "ptNone", "ptNone", "ptNone" },
        { 1u, "GetDistance", "ptObjectReference", "ptNone", "ptNone" },
        { 5u, "GetLocked", "ptNone", "ptNone", "ptNone" },
        { 6u, "GetPos", "ptAxis", "ptNone", "ptNone" },
        { 8u, "GetAngle", "ptAxis", "ptNone", "ptNone" },
        { 10u, "GetStartingPos", "ptAxis", "ptNone", "ptNone" },
        { 11u, "GetStartingAngle", "ptAxis", "ptNone", "ptNone" },
        { 12u, "GetSecondsPassed", "ptNone", "ptNone", "ptNone" },
        { 14u, "GetActorValue", "ptActorValue", "ptNone", "ptNone" },
        { 18u, "GetCurrentTime", "ptNone", "ptNone", "ptNone" },
        { 24u, "GetScale", "ptNone", "ptNone", "ptNone" },
        { 25u, "IsMoving", "ptNone", "ptNone", "ptNone" },
        { 26u, "IsTurning", "ptNone", "ptNone", "ptNone" },
        { 27u, "GetLineOfSight", "ptObjectReference", "ptNone", "ptNone" },
        { 32u, "GetInSameCell", "ptObjectReference", "ptNone", "ptNone" },
        { 35u, "GetDisabled", "ptNone", "ptNone", "ptNone" },
        { 36u, "MenuMode", "ptInteger", "ptNone", "ptNone" },
        { 39u, "GetDisease", "ptNone", "ptNone", "ptNone" },
        { 41u, "GetClothingValue", "ptNone", "ptNone", "ptNone" },
        { 42u, "SameFaction", "ptActor", "ptNone", "ptNone" },
        { 43u, "SameRace", "ptActor", "ptNone", "ptNone" },
        { 44u, "SameSex", "ptActor", "ptNone", "ptNone" },
        { 45u, "GetDetected", "ptActor", "ptNone", "ptNone" },
        { 46u, "GetDead", "ptNone", "ptNone", "ptNone" },
        { 47u, "GetItemCount", "ptInventoryObject", "ptNone", "ptNone" },
        { 48u, "GetGold", "ptNone", "ptNone", "ptNone" },
        { 49u, "GetSleeping", "ptNone", "ptNone", "ptNone" },
        { 50u, "GetTalkedToPC", "ptNone", "ptNone", "ptNone" },
        { 53u, "GetScriptVariable", "ptObjectReference", "ptVariableName", "ptNone" },
        { 56u, "GetQuestRunning", "ptQuest", "ptNone", "ptNone" },
        { 58u, "GetStage", "ptQuest", "ptNone", "ptNone" },
        { 59u, "GetStageDone", "ptQuest", "ptQuestStage", "ptNone" },
        { 60u, "GetFactionRankDifference", "ptFaction", "ptActor", "ptNone" },
        { 61u, "GetAlarmed", "ptNone", "ptNone", "ptNone" },
        { 62u, "IsRaining", "ptNone", "ptNone", "ptNone" },
        { 63u, "GetAttacked", "ptNone", "ptNone", "ptNone" },
        { 64u, "GetIsCreature", "ptNone", "ptNone", "ptNone" },
        { 65u, "GetLockLevel", "ptNone", "ptNone", "ptNone" },
        { 66u, "GetShouldAttack", "ptActor", "ptNone", "ptNone" },
        { 67u, "GetInCell", "ptCell", "ptNone", "ptNone" },
        { 68u, "GetIsClass", "ptClass", "ptNone", "ptNone" },
        { 69u, "GetIsRace", "ptRace", "ptNone", "ptNone" },
        { 70u, "GetIsSex", "ptSex", "ptNone", "ptNone" },
        { 71u, "GetInFaction", "ptFaction", "ptNone", "ptNone" },
        { 72u, "GetIsID", "ptReferencableObject", "ptNone", "ptNone" },
        { 73u, "GetFactionRank", "ptFaction", "ptNone", "ptNone" },
        { 74u, "GetGlobalValue", "ptGlobal", "ptNone", "ptNone" },
        { 75u, "IsSnowing", "ptNone", "ptNone", "ptNone" },
        { 77u, "GetRandomPercent", "ptNone", "ptNone", "ptNone" },
        { 79u, "GetQuestVariable", "ptQuest", "ptVariableName", "ptNone" },
        { 80u, "GetLevel", "ptNone", "ptNone", "ptNone" },
        { 81u, "IsRotating", "ptNone", "ptNone", "ptNone" },
        { 84u, "GetDeadCount", "ptActorBase", "ptNone", "ptNone" },
        { 91u, "GetIsAlerted", "ptNone", "ptNone", "ptNone" },
        { 98u, "GetPlayerControlsDisabled", "ptInteger", "ptInteger", "ptNone" },
        { 99u, "GetHeadingAngle", "ptObjectReference", "ptNone", "ptNone" },
        { 101u, "IsWeaponMagicOut", "ptNone", "ptNone", "ptNone" },
        { 102u, "IsTorchOut", "ptNone", "ptNone", "ptNone" },
        { 103u, "IsShieldOut", "ptNone", "ptNone", "ptNone" },
        { 106u, "IsFacingUp", "ptNone", "ptNone", "ptNone" },
        { 107u, "GetKnockedState", "ptNone", "ptNone", "ptNone" },
        { 108u, "GetWeaponAnimType", "ptNone", "ptNone", "ptNone" },
        { 109u, "IsWeaponSkillType", "ptActorValue", "ptNone", "ptNone" },
        { 110u, "GetCurrentAIPackage", "ptNone", "ptNone", "ptNone" },
        { 111u, "IsWaiting", "ptNone", "ptNone", "ptNone" },
        { 112u, "IsIdlePlaying", "ptNone", "ptNone", "ptNone" },
        { 116u, "IsIntimidatebyPlayer", "ptNone", "ptNone", "ptNone" },
        { 117u, "IsPlayerInRegion", "ptRegion", "ptNone", "ptNone" },
        { 118u, "GetActorAggroRadiusViolated", "ptNone", "ptNone", "ptNone" },
        { 122u, "GetCrime", "ptActor", "ptCrimeType", "ptNone" },
        { 123u, "IsGreetingPlayer", "ptNone", "ptNone", "ptNone" },
        { 125u, "IsGuard", "ptNone", "ptNone", "ptNone" },
        { 127u, "HasBeenEaten", "ptNone", "ptNone", "ptNone" },
        { 128u, "GetStaminaPercentage", "ptNone", "ptNone", "ptNone" },
        { 129u, "GetPCIsClass", "ptClass", "ptNone", "ptNone" },
        { 130u, "GetPCIsRace", "ptRace", "ptNone", "ptNone" },
        { 131u, "GetPCIsSex", "ptSex", "ptNone", "ptNone" },
        { 132u, "GetPCInFaction", "ptFaction", "ptNone", "ptNone" },
        { 133u, "SameFactionAsPC", "ptNone", "ptNone", "ptNone" },
        { 134u, "SameRaceAsPC", "ptNone", "ptNone", "ptNone" },
        { 135u, "SameSexAsPC", "ptNone", "ptNone", "ptNone" },
        { 136u, "GetIsReference", "ptObjectReference", "ptNone", "ptNone" },
        { 141u, "IsTalking", "ptNone", "ptNone", "ptNone" },
        { 142u, "GetWalkSpeed", "ptNone", "ptNone", "ptNone" },
        { 143u, "GetCurrentAIProcedure", "ptNone", "ptNone", "ptNone" },
        { 144u, "GetTrespassWarningLevel", "ptNone", "ptNone", "ptNone" },
        { 145u, "IsTrespassing", "ptNone", "ptNone", "ptNone" },
        { 146u, "IsInMyOwnedCell", "ptNone", "ptNone", "ptNone" },
        { 147u, "GetWindSpeed", "ptNone", "ptNone", "ptNone" },
        { 148u, "GetCurrentWeatherPercent", "ptNone", "ptNone", "ptNone" },
        { 149u, "GetIsCurrentWeather", "ptWeather", "ptNone", "ptNone" },
        { 150u, "IsContinuingPackagePCNear", "ptNone", "ptNone", "ptNone" },
        { 152u, "GetIsCrimeFaction", "ptFaction", "ptNone", "ptNone" },
        { 153u, "CanHaveFlames", "ptNone", "ptNone", "ptNone" },
        { 154u, "HasFlames", "ptNone", "ptNone", "ptNone" },
        { 157u, "GetOpenState", "ptNone", "ptNone", "ptNone" },
        { 159u, "GetSitting", "ptNone", "ptNone", "ptNone" },
        { 161u, "GetIsCurrentPackage", "ptPackage", "ptNone", "ptNone" },
        { 162u, "IsCurrentFurnitureRef", "ptObjectReference", "ptNone", "ptNone" },
        { 163u, "IsCurrentFurnitureObj", "ptFurniture", "ptNone", "ptNone" },
        { 170u, "GetDayOfWeek", "ptNone", "ptNone", "ptNone" },
        { 172u, "GetTalkedToPCParam", "ptActor", "ptNone", "ptNone" },
        { 175u, "IsPCSleeping", "ptNone", "ptNone", "ptNone" },
        { 176u, "IsPCAMurderer", "ptNone", "ptNone", "ptNone" },
        { 180u, "HasSameEditorLocAsRef", "ptObjectReference", "ptKeyword", "ptNone" },
        { 181u, "HasSameEditorLocAsRefAlias", "ptAlias", "ptKeyword", "ptNone" },
        { 182u, "GetEquipped", "ptInventoryObject", "ptNone", "ptNone" },
        { 185u, "IsSwimming", "ptNone", "ptNone", "ptNone" },
        { 190u, "GetAmountSoldStolen", "ptNone", "ptNone", "ptNone" },
        { 192u, "GetIgnoreCrime", "ptNone", "ptNone", "ptNone" },
        { 193u, "GetPCExpelled", "ptFaction", "ptNone", "ptNone" },
        { 195u, "GetPCFactionMurder", "ptFaction", "ptNone", "ptNone" },
        { 197u, "GetPCEnemyofFaction", "ptFaction", "ptNone", "ptNone" },
        { 199u, "GetPCFactionAttack", "ptFaction", "ptNone", "ptNone" },
        { 203u, "GetDestroyed", "ptNone", "ptNone", "ptNone" },
        { 214u, "HasMagicEffect", "ptMagicEffect", "ptNone", "ptNone" },
        { 215u, "GetDefaultOpen", "ptNone", "ptNone", "ptNone" },
        { 219u, "GetAnimAction", "ptNone", "ptNone", "ptNone" },
        { 223u, "IsSpellTarget", "ptMagicItem", "ptNone", "ptNone" },
        { 224u, "GetVATSMode", "ptNone", "ptNone", "ptNone" },
        { 225u, "GetPersuasionNumber", "ptNone", "ptNone", "ptNone" },
        { 226u, "GetVampireFeed", "ptNone", "ptNone", "ptNone" },
        { 227u, "GetCannibal", "ptNone", "ptNone", "ptNone" },
        { 228u, "GetIsClassDefault", "ptClass", "ptNone", "ptNone" },
        { 229u, "GetClassDefaultMatch", "ptNone", "ptNone", "ptNone" },
        { 230u, "GetInCellParam", "ptCell", "ptObjectReference", "ptNone" },
        { 235u, "GetVatsTargetHeight", "ptNone", "ptNone", "ptNone" },
        { 237u, "GetIsGhost", "ptNone", "ptNone", "ptNone" },
        { 242u, "GetUnconscious", "ptNone", "ptNone", "ptNone" },
        { 244u, "GetRestrained", "ptNone", "ptNone", "ptNone" },
        { 246u, "GetIsUsedItem", "ptReferencableObject", "ptNone", "ptNone" },
        { 247u, "GetIsUsedItemType", "ptFormType", "ptNone", "ptNone" },
        { 248u, "IsScenePlaying", "ptScene", "ptNone", "ptNone" },
        { 249u, "IsInDialogueWithPlayer", "ptNone", "ptNone", "ptNone" },
        { 250u, "GetLocationCleared", "ptLocation", "ptNone", "ptNone" },
        { 254u, "GetIsPlayableRace", "ptNone", "ptNone", "ptNone" },
        { 255u, "GetOffersServicesNow", "ptNone", "ptNone", "ptNone" },
        { 258u, "HasAssociationType", "ptActor", "ptAssociationType", "ptNone" },
        { 259u, "HasFamilyRelationship", "ptActor", "ptNone", "ptNone" },
        { 261u, "HasParentRelationship", "ptActor", "ptNone", "ptNone" },
        { 262u, "IsWarningAbout", "ptFormList", "ptNone", "ptNone" },
        { 263u, "IsWeaponOut", "ptNone", "ptNone", "ptNone" },
        { 264u, "HasSpell", "ptMagicItem", "ptNone", "ptNone" },
        { 265u, "IsTimePassing", "ptNone", "ptNone", "ptNone" },
        { 266u, "IsPleasant", "ptNone", "ptNone", "ptNone" },
        { 267u, "IsCloudy", "ptNone", "ptNone", "ptNone" },
        { 274u, "IsSmallBump", "ptNone", "ptNone", "ptNone" },
        { 277u, "GetBaseActorValue", "ptActorValue", "ptNone", "ptNone" },
        { 278u, "IsOwner", "ptOwner", "ptNone", "ptNone" },
        { 280u, "IsCellOwner", "ptCell", "ptOwner", "ptNone" },
        { 282u, "IsHorseStolen", "ptNone", "ptNone", "ptNone" },
        { 285u, "IsLeftUp", "ptNone", "ptNone", "ptNone" },
        { 286u, "IsSneaking", "ptNone", "ptNone", "ptNone" },
        { 287u, "IsRunning", "ptNone", "ptNone", "ptNone" },
        { 288u, "GetFriendHit", "ptNone", "ptNone", "ptNone" },
        { 289u, "IsInCombat", "ptInteger", "ptNone", "ptNone" },
        { 300u, "IsInInterior", "ptNone", "ptNone", "ptNone" },
        { 304u, "IsWaterObject", "ptNone", "ptNone", "ptNone" },
        { 305u, "GetPlayerAction", "ptNone", "ptNone", "ptNone" },
        { 306u, "IsActorUsingATorch", "ptNone", "ptNone", "ptNone" },
        { 309u, "IsXBox", "ptNone", "ptNone", "ptNone" },
        { 310u, "GetInWorldspace", "ptWorldSpace", "ptNone", "ptNone" },
        { 312u, "GetPCMiscStat", "ptMiscStat", "ptNone", "ptNone" },
        { 313u, "GetPairedAnimation", "ptNone", "ptNone", "ptNone" },
        { 314u, "IsActorAVictim", "ptNone", "ptNone", "ptNone" },
        { 315u, "GetTotalPersuasionNumber", "ptNone", "ptNone", "ptNone" },
        { 318u, "GetIdleDoneOnce", "ptNone", "ptNone", "ptNone" },
        { 320u, "GetNoRumors", "ptNone", "ptNone", "ptNone" },
        { 323u, "GetCombatState", "ptNone", "ptNone", "ptNone" },
        { 325u, "GetWithinPackageLocation", "ptPackdata", "ptNone", "ptNone" },
        { 327u, "IsRidingMount", "ptNone", "ptNone", "ptNone" },
        { 329u, "IsFleeing", "ptNone", "ptNone", "ptNone" },
        { 332u, "IsInDangerousWater", "ptNone", "ptNone", "ptNone" },
        { 338u, "GetIgnoreFriendlyHits", "ptNone", "ptNone", "ptNone" },
        { 339u, "IsPlayersLastRiddenMount", "ptNone", "ptNone", "ptNone" },
        { 353u, "IsActor", "ptNone", "ptNone", "ptNone" },
        { 354u, "IsEssential", "ptNone", "ptNone", "ptNone" },
        { 358u, "IsPlayerMovingIntoNewSpace", "ptNone", "ptNone", "ptNone" },
        { 359u, "GetInCurrentLoc", "ptLocation", "ptNone", "ptNone" },
        { 360u, "GetInCurrentLocAlias", "ptAlias", "ptNone", "ptNone" },
        { 361u, "GetTimeDead", "ptNone", "ptNone", "ptNone" },
        { 362u, "HasLinkedRef", "ptKeyword", "ptNone", "ptNone" },
        { 365u, "IsChild", "ptNone", "ptNone", "ptNone" },
        { 366u, "GetStolenItemValueNoCrime", "ptFaction", "ptNone", "ptNone" },
        { 367u, "GetLastPlayerAction", "ptNone", "ptNone", "ptNone" },
        { 368u, "IsPlayerActionActive", "ptInteger", "ptNone", "ptNone" },
        { 370u, "IsTalkingActivatorActor", "ptActor", "ptNone", "ptNone" },
        { 372u, "IsInList", "ptFormList", "ptNone", "ptNone" },
        { 373u, "GetStolenItemValue", "ptFaction", "ptNone", "ptNone" },
        { 375u, "GetCrimeGoldViolent", "ptNone", "ptNone", "ptNone" },
        { 376u, "GetCrimeGoldNonviolent", "ptNone", "ptNone", "ptNone" },
        { 378u, "HasShout", "ptShout", "ptNone", "ptNone" },
        { 381u, "GetHasNote", "ptInteger", "ptNone", "ptNone" },
        { 390u, "GetHitLocation", "ptNone", "ptNone", "ptNone" },
        { 391u, "IsPC1stPerson", "ptNone", "ptNone", "ptNone" },
        { 396u, "GetCauseofDeath", "ptNone", "ptNone", "ptNone" },
        { 397u, "IsLimbGone", "ptInteger", "ptNone", "ptNone" },
        { 398u, "IsWeaponInList", "ptFormList", "ptNone", "ptNone" },
        { 402u, "IsBribedbyPlayer", "ptNone", "ptNone", "ptNone" },
        { 403u, "GetRelationshipRank", "ptObjectReference", "ptNone", "ptNone" },
        { 407u, "GetVATSValue", "ptVATSValueFunction", "ptVATSValueParam", "ptNone" },
        { 408u, "IsKiller", "ptActor", "ptNone", "ptNone" },
        { 409u, "IsKillerObject", "ptFormList", "ptNone", "ptNone" },
        { 410u, "GetFactionCombatReaction", "ptFaction", "ptFaction", "ptNone" },
        { 414u, "Exists", "ptObjectReference", "ptNone", "ptNone" },
        { 415u, "GetGroupMemberCount", "ptNone", "ptNone", "ptNone" },
        { 416u, "GetGroupTargetCount", "ptNone", "ptNone", "ptNone" },
        { 426u, "GetIsVoiceType", "ptVoiceType", "ptNone", "ptNone" },
        { 427u, "GetPlantedExplosive", "ptNone", "ptNone", "ptNone" },
        { 429u, "IsScenePackageRunning", "ptNone", "ptNone", "ptNone" },
        { 430u, "GetHealthPercentage", "ptNone", "ptNone", "ptNone" },
        { 432u, "GetIsObjectType", "ptFormType", "ptNone", "ptNone" },
        { 434u, "GetDialogueEmotion", "ptNone", "ptNone", "ptNone" },
        { 435u, "GetDialogueEmotionValue", "ptNone", "ptNone", "ptNone" },
        { 437u, "GetIsCreatureType", "ptInteger", "ptNone", "ptNone" },
        { 444u, "GetInCurrentLocFormList", "ptFormList", "ptNone", "ptNone" },
        { 445u, "GetInZone", "ptEncounterZone", "ptNone", "ptNone" },
        { 446u, "GetVelocity", "ptAxis", "ptNone", "ptNone" },
        { 447u, "GetGraphVariableFloat", "ptVariableName", "ptNone", "ptNone" },
        { 448u, "HasPerk", "ptPerk", "ptInteger", "ptNone" },
        { 449u, "GetFactionRelation", "ptActor", "ptNone", "ptNone" },
        { 450u, "IsLastIdlePlayed", "ptIdleForm", "ptNone", "ptNone" },
        { 453u, "GetPlayerTeammate", "ptNone", "ptNone", "ptNone" },
        { 454u, "GetPlayerTeammateCount", "ptNone", "ptNone", "ptNone" },
        { 458u, "GetActorCrimePlayerEnemy", "ptNone", "ptNone", "ptNone" },
        { 459u, "GetCrimeGold", "ptNone", "ptNone", "ptNone" },
        { 463u, "IsPlayerGrabbedRef", "ptObjectReference", "ptNone", "ptNone" },
        { 465u, "GetKeywordItemCount", "ptKeyword", "ptNone", "ptNone" },
        { 470u, "GetDestructionStage", "ptNone", "ptNone", "ptNone" },
        { 473u, "GetIsAlignment", "ptAlignment", "ptNone", "ptNone" },
        { 476u, "IsProtected", "ptNone", "ptNone", "ptNone" },
        { 477u, "GetThreatRatio", "ptActor", "ptNone", "ptNone" },
        { 479u, "GetIsUsedItemEquipType", "ptEquipType", "ptNone", "ptNone" },
        { 487u, "IsCarryable", "ptNone", "ptNone", "ptNone" },
        { 488u, "GetConcussed", "ptNone", "ptNone", "ptNone" },
        { 491u, "GetMapMarkerVisible", "ptNone", "ptNone", "ptNone" },
        { 493u, "PlayerKnows", "ptKnowable", "ptNone", "ptNone" },
        { 494u, "GetPermanentActorValue", "ptActorValue", "ptNone", "ptNone" },
        { 495u, "GetKillingBlowLimb", "ptNone", "ptNone", "ptNone" },
        { 497u, "CanPayCrimeGold", "ptNone", "ptNone", "ptNone" },
        { 499u, "GetDaysInJail", "ptNone", "ptNone", "ptNone" },
        { 500u, "EPAlchemyGetMakingPoison", "ptNone", "ptNone", "ptNone" },
        { 501u, "EPAlchemyEffectHasKeyword", "ptKeyword", "ptNone", "ptNone" },
        { 503u, "GetAllowWorldInteractions", "ptNone", "ptNone", "ptNone" },
        { 508u, "GetLastHitCritical", "ptNone", "ptNone", "ptNone" },
        { 513u, "IsCombatTarget", "ptActor", "ptNone", "ptNone" },
        { 515u, "GetVATSRightAreaFree", "ptObjectReference", "ptNone", "ptNone" },
        { 516u, "GetVATSLeftAreaFree", "ptObjectReference", "ptNone", "ptNone" },
        { 517u, "GetVATSBackAreaFree", "ptObjectReference", "ptNone", "ptNone" },
        { 518u, "GetVATSFrontAreaFree", "ptObjectReference", "ptNone", "ptNone" },
        { 519u, "GetLockIsBroken", "ptNone", "ptNone", "ptNone" },
        { 520u, "IsPS3", "ptNone", "ptNone", "ptNone" },
        { 521u, "IsWin32", "ptNone", "ptNone", "ptNone" },
        { 522u, "GetVATSRightTargetVisible", "ptObjectReference", "ptNone", "ptNone" },
        { 523u, "GetVATSLeftTargetVisible", "ptObjectReference", "ptNone", "ptNone" },
        { 524u, "GetVATSBackTargetVisible", "ptObjectReference", "ptNone", "ptNone" },
        { 525u, "GetVATSFrontTargetVisible", "ptObjectReference", "ptNone", "ptNone" },
        { 528u, "IsInCriticalStage", "ptCriticalStage", "ptNone", "ptNone" },
        { 530u, "GetXPForNextLevel", "ptNone", "ptNone", "ptNone" },
        { 533u, "GetInfamy", "ptNone", "ptNone", "ptNone" },
        { 534u, "GetInfamyViolent", "ptNone", "ptNone", "ptNone" },
        { 535u, "GetInfamyNonViolent", "ptNone", "ptNone", "ptNone" },
        { 543u, "GetQuestCompleted", "ptQuest", "ptNone", "ptNone" },
        { 547u, "IsGoreDisabled", "ptNone", "ptNone", "ptNone" },
        { 550u, "IsSceneActionComplete", "ptScene", "ptInteger", "ptNone" },
        { 552u, "GetSpellUsageNum", "ptMagicItem", "ptNone", "ptNone" },
        { 554u, "GetActorsInHigh", "ptNone", "ptNone", "ptNone" },
        { 555u, "HasLoaded3D", "ptNone", "ptNone", "ptNone" },
        { 560u, "HasKeyword", "ptKeyword", "ptNone", "ptNone" },
        { 561u, "HasRefType", "ptRefType", "ptNone", "ptNone" },
        { 562u, "LocationHasKeyword", "ptKeyword", "ptNone", "ptNone" },
        { 563u, "LocationHasRefType", "ptRefType", "ptNone", "ptNone" },
        { 565u, "GetIsEditorLocation", "ptLocation", "ptNone", "ptNone" },
        { 566u, "GetIsAliasRef", "ptAlias", "ptNone", "ptNone" },
        { 567u, "GetIsEditorLocAlias", "ptAlias", "ptNone", "ptNone" },
        { 568u, "IsSprinting", "ptNone", "ptNone", "ptNone" },
        { 569u, "IsBlocking", "ptNone", "ptNone", "ptNone" },
        { 570u, "HasEquippedSpell", "ptCastingSource", "ptNone", "ptNone" },
        { 571u, "GetCurrentCastingType", "ptCastingSource", "ptNone", "ptNone" },
        { 572u, "GetCurrentDeliveryType", "ptCastingSource", "ptNone", "ptNone" },
        { 574u, "GetAttackState", "ptNone", "ptNone", "ptNone" },
        { 576u, "GetEventData", "ptEvent", "ptEventData", "ptNone" },
        { 577u, "IsCloserToAThanB", "ptObjectReference", "ptObjectReference", "ptNone" },
        { 579u, "GetEquippedShout", "ptShout", "ptNone", "ptNone" },
        { 580u, "IsBleedingOut", "ptNone", "ptNone", "ptNone" },
        { 584u, "GetRelativeAngle", "ptObjectReference", "ptAxis", "ptNone" },
        { 589u, "GetMovementDirection", "ptNone", "ptNone", "ptNone" },
        { 590u, "IsInScene", "ptNone", "ptNone", "ptNone" },
        { 591u, "GetRefTypeDeadCount", "ptLocation", "ptRefType", "ptNone" },
        { 592u, "GetRefTypeAliveCount", "ptLocation", "ptRefType", "ptNone" },
        { 594u, "GetIsFlying", "ptNone", "ptNone", "ptNone" },
        { 595u, "IsCurrentSpell", "ptMagicItem", "ptCastingSource", "ptNone" },
        { 596u, "SpellHasKeyword", "ptCastingSource", "ptKeyword", "ptNone" },
        { 597u, "GetEquippedItemType", "ptCastingSource", "ptNone", "ptNone" },
        { 598u, "GetLocationAliasCleared", "ptAlias", "ptNone", "ptNone" },
        { 600u, "GetLocAliasRefTypeDeadCount", "ptAlias", "ptRefType", "ptNone" },
        { 601u, "GetLocAliasRefTypeAliveCount", "ptAlias", "ptRefType", "ptNone" },
        { 602u, "IsWardState", "ptWardState", "ptNone", "ptNone" },
        { 603u, "IsInSameCurrentLocAsRef", "ptObjectReference", "ptKeyword", "ptNone" },
        { 604u, "IsInSameCurrentLocAsRefAlias", "ptAlias", "ptKeyword", "ptNone" },
        { 605u, "LocAliasIsLocation", "ptAlias", "ptLocation", "ptNone" },
        { 606u, "GetKeywordDataForLocation", "ptLocation", "ptKeyword", "ptNone" },
        { 608u, "GetKeywordDataForAlias", "ptAlias", "ptKeyword", "ptNone" },
        { 610u, "LocAliasHasKeyword", "ptAlias", "ptKeyword", "ptNone" },
        { 611u, "IsNullPackageData", "ptPackdata", "ptNone", "ptNone" },
        { 612u, "GetNumericPackageData", "ptInteger", "ptNone", "ptNone" },
        { 613u, "IsFurnitureAnimType", "ptFurnitureAnim", "ptNone", "ptNone" },
        { 614u, "IsFurnitureEntryType", "ptFurnitureEntry", "ptNone", "ptNone" },
        { 615u, "GetHighestRelationshipRank", "ptNone", "ptNone", "ptNone" },
        { 616u, "GetLowestRelationshipRank", "ptNone", "ptNone", "ptNone" },
        { 617u, "HasAssociationTypeAny", "ptAssociationType", "ptNone", "ptNone" },
        { 618u, "HasFamilyRelationshipAny", "ptNone", "ptNone", "ptNone" },
        { 619u, "GetPathingTargetOffset", "ptAxis", "ptNone", "ptNone" },
        { 620u, "GetPathingTargetAngleOffset", "ptAxis", "ptNone", "ptNone" },
        { 621u, "GetPathingTargetSpeed", "ptNone", "ptNone", "ptNone" },
        { 622u, "GetPathingTargetSpeedAngle", "ptAxis", "ptNone", "ptNone" },
        { 623u, "GetMovementSpeed", "ptNone", "ptNone", "ptNone" },
        { 624u, "GetInContainer", "ptObjectReference", "ptNone", "ptNone" },
        { 625u, "IsLocationLoaded", "ptLocation", "ptNone", "ptNone" },
        { 626u, "IsLocAliasLoaded", "ptAlias", "ptNone", "ptNone" },
        { 627u, "IsDualCasting", "ptNone", "ptNone", "ptNone" },
        { 629u, "GetVMQuestVariable", "ptQuest", "ptVariableName", "ptNone" },
        { 630u, "GetVMScriptVariable", "ptObjectReference", "ptVariableName", "ptNone" },
        { 631u, "IsEnteringInteractionQuick", "ptNone", "ptNone", "ptNone" },
        { 632u, "IsCasting", "ptNone", "ptNone", "ptNone" },
        { 633u, "GetFlyingState", "ptNone", "ptNone", "ptNone" },
        { 635u, "IsInFavorState", "ptNone", "ptNone", "ptNone" },
        { 636u, "HasTwoHandedWeaponEquipped", "ptNone", "ptNone", "ptNone" },
        { 637u, "IsExitingInstant", "ptNone", "ptNone", "ptNone" },
        { 638u, "IsInFriendStateWithPlayer", "ptNone", "ptNone", "ptNone" },
        { 639u, "GetWithinDistance", "ptObjectReference", "ptFloat", "ptNone" },
        { 640u, "GetActorValuePercent", "ptActorValue", "ptNone", "ptNone" },
        { 641u, "IsUnique", "ptNone", "ptNone", "ptNone" },
        { 642u, "GetLastBumpDirection", "ptNone", "ptNone", "ptNone" },
        { 644u, "IsInFurnitureState", "ptFurnitureAnim", "ptNone", "ptNone" },
        { 645u, "GetIsInjured", "ptNone", "ptNone", "ptNone" },
        { 646u, "GetIsCrashLandRequest", "ptNone", "ptNone", "ptNone" },
        { 647u, "GetIsHastyLandRequest", "ptNone", "ptNone", "ptNone" },
        { 650u, "IsLinkedTo", "ptObjectReference", "ptKeyword", "ptNone" },
        { 651u, "GetKeywordDataForCurrentLocation", "ptKeyword", "ptNone", "ptNone" },
        { 652u, "GetInSharedCrimeFaction", "ptObjectReference", "ptNone", "ptNone" },
        { 654u, "GetBribeSuccess", "ptNone", "ptNone", "ptNone" },
        { 655u, "GetIntimidateSuccess", "ptNone", "ptNone", "ptNone" },
        { 656u, "GetArrestedState", "ptNone", "ptNone", "ptNone" },
        { 657u, "GetArrestingActor", "ptNone", "ptNone", "ptNone" },
        { 659u, "EPTemperingItemIsEnchanted", "ptNone", "ptNone", "ptNone" },
        { 660u, "EPTemperingItemHasKeyword", "ptKeyword", "ptNone", "ptNone" },
        { 664u, "GetReplacedItemType", "ptCastingSource", "ptNone", "ptNone" },
        { 672u, "IsAttacking", "ptNone", "ptNone", "ptNone" },
        { 673u, "IsPowerAttacking", "ptNone", "ptNone", "ptNone" },
        { 674u, "IsLastHostileActor", "ptNone", "ptNone", "ptNone" },
        { 675u, "GetGraphVariableInt", "ptVariableName", "ptNone", "ptNone" },
        { 676u, "GetCurrentShoutVariation", "ptNone", "ptNone", "ptNone" },
        { 678u, "ShouldAttackKill", "ptActor", "ptNone", "ptNone" },
        { 680u, "GetActivatorHeight", "ptNone", "ptNone", "ptNone" },
        { 681u, "EPMagic_IsAdvanceSkill", "ptActorValue", "ptNone", "ptNone" },
        { 682u, "WornHasKeyword", "ptKeyword", "ptNone", "ptNone" },
        { 683u, "GetPathingCurrentSpeed", "ptNone", "ptNone", "ptNone" },
        { 684u, "GetPathingCurrentSpeedAngle", "ptAxis", "ptNone", "ptNone" },
        { 691u, "EPModSkillUsage_AdvanceObjectHasKeyword", "ptKeyword", "ptNone", "ptNone" },
        { 692u, "EPModSkillUsage_IsAdvanceAction", "ptAdvanceAction", "ptNone", "ptNone" },
        { 693u, "EPMagic_SpellHasKeyword", "ptKeyword", "ptNone", "ptNone" },
        { 694u, "GetNoBleedoutRecovery", "ptNone", "ptNone", "ptNone" },
        { 696u, "EPMagic_SpellHasSkill", "ptActorValue", "ptNone", "ptNone" },
        { 697u, "IsAttackType", "ptKeyword", "ptNone", "ptNone" },
        { 698u, "IsAllowedToFly", "ptNone", "ptNone", "ptNone" },
        { 699u, "HasMagicEffectKeyword", "ptKeyword", "ptNone", "ptNone" },
        { 700u, "IsCommandedActor", "ptNone", "ptNone", "ptNone" },
        { 701u, "IsStaggered", "ptNone", "ptNone", "ptNone" },
        { 702u, "IsRecoiling", "ptNone", "ptNone", "ptNone" },
        { 703u, "IsExitingInteractionQuick", "ptNone", "ptNone", "ptNone" },
        { 704u, "IsPathing", "ptNone", "ptNone", "ptNone" },
        { 705u, "GetShouldHelp", "ptActor", "ptNone", "ptNone" },
        { 706u, "HasBoundWeaponEquipped", "ptCastingSource", "ptNone", "ptNone" },
        { 707u, "GetCombatTargetHasKeyword", "ptKeyword", "ptNone", "ptNone" },
        { 709u, "GetCombatGroupMemberCount", "ptNone", "ptNone", "ptNone" },
        { 710u, "IsIgnoringCombat", "ptNone", "ptNone", "ptNone" },
        { 711u, "GetLightLevel", "ptNone", "ptNone", "ptNone" },
        { 713u, "SpellHasCastingPerk", "ptPerk", "ptNone", "ptNone" },
        { 714u, "IsBeingRidden", "ptNone", "ptNone", "ptNone" },
        { 715u, "IsUndead", "ptNone", "ptNone", "ptNone" },
        { 716u, "GetRealHoursPassed", "ptNone", "ptNone", "ptNone" },
        { 718u, "IsUnlockedDoor", "ptNone", "ptNone", "ptNone" },
        { 719u, "IsHostileToActor", "ptActor", "ptNone", "ptNone" },
        { 720u, "GetTargetHeight", "ptObjectReference", "ptNone", "ptNone" },
        { 721u, "IsPoison", "ptNone", "ptNone", "ptNone" },
        { 722u, "WornApparelHasKeywordCount", "ptKeyword", "ptNone", "ptNone" },
        { 723u, "GetItemHealthPercent", "ptNone", "ptNone", "ptNone" },
        { 724u, "EffectWasDualCast", "ptNone", "ptNone", "ptNone" },
        { 725u, "GetKnockedStateEnum", "ptNone", "ptNone", "ptNone" },
        { 726u, "DoesNotExist", "ptNone", "ptNone", "ptNone" },
        { 730u, "IsOnFlyingMount", "ptNone", "ptNone", "ptNone" },
        { 731u, "CanFlyHere", "ptNone", "ptNone", "ptNone" },
        { 732u, "IsFlyingMountPatrolQueud", "ptNone", "ptNone", "ptNone" },
        { 733u, "IsFlyingMountFastTravelling", "ptNone", "ptNone", "ptNone" },
        { 734u, "IsOverEncumbered", "ptNone", "ptNone", "ptNone" },
        { 735u, "GetActorWarmth", "ptNone", "ptNone", "ptNone" },
        { 1024u, "GetSKSEVersion", "ptNone", "ptNone", "ptNone" },
        { 1025u, "GetSKSEVersionMinor", "ptNone", "ptNone", "ptNone" },
        { 1026u, "GetSKSEVersionBeta", "ptNone", "ptNone", "ptNone" },
        { 1027u, "GetSKSERelease", "ptNone", "ptNone", "ptNone" },
        { 1028u, "ClearInvalidRegistrations", "ptNone", "ptNone", "ptNone" },
    }};

    bool IsOneOf(const std::string_view rawType, const std::initializer_list<std::string_view> values)
    {
        return std::ranges::any_of(values, [rawType](const std::string_view value) {
            return rawType == value;
        });
    }
}

namespace ConditionCatalog {
    std::span<const FunctionInfo> GetFunctions()
    {
        return FUNCTIONS;
    }

    const FunctionInfo* FindFunction(const std::uint32_t id)
    {
        const auto it = std::ranges::find(FUNCTIONS, id, &FunctionInfo::id);
        return it != FUNCTIONS.end() ? std::addressof(*it) : nullptr;
    }

    const char* GetFunctionName(const std::uint32_t id)
    {
        const auto* info = FindFunction(id);
        return info ? info->name : "Unknown";
    }

    bool IsIntegerParam(const std::string_view rawType)
    {
        return IsOneOf(rawType, {
            "ptActorValue", "ptAdvanceAction", "ptAlignment", "ptAxis", "ptCastingSource",
            "ptCrimeType", "ptCriticalStage", "ptEvent", "ptEventData", "ptFormType",
            "ptFurnitureAnim", "ptFurnitureEntry", "ptInteger", "ptMiscStat", "ptQuestStage",
            "ptSex", "ptVATSValueFunction", "ptVATSValueParam", "ptWardState"
        });
    }

    bool IsFloatParam(const std::string_view rawType)
    {
        return rawType == "ptFloat";
    }

    bool IsStringParam(const std::string_view rawType)
    {
        return rawType == "ptVariableName";
    }

    bool IsFormParam(const std::string_view rawType)
    {
        return !rawType.empty() && rawType != "ptNone" && !IsIntegerParam(rawType) && !IsFloatParam(rawType) && !IsStringParam(rawType);
    }
}
